"""Dashboard.md: the whole semester at a glance, rewritten on every sync."""

from __future__ import annotations

import sqlite3
from datetime import datetime, timedelta
from pathlib import Path

from . import db
from . import grades
from .config import Config
from .db import EFFECTIVE, connector_health


def write(conn: sqlite3.Connection, cfg: Config, now: datetime) -> Path:
    from . import vault

    return vault.write_file(cfg.vault / "Dashboard.md", render(conn, cfg, now))


def render(conn: sqlite3.Connection, cfg: Config, now: datetime) -> str:
    lines = [
        "---",
        "type: oso-dashboard",
        f"generated: {now.isoformat(timespec='minutes')}",
        "---",
        "",
        "# Dashboard",
        "",
        "Generated by Oso on every sync. See [[Today]] for what to do today.",
        "",
        "## Courses",
        "",
        "| Course | Standing | Graded | Next due | Open items |",
        "| --- | --- | --- | --- | --- |",
    ]
    for c in sorted((c for c in cfg.courses if not c.finished), key=lambda c: c.name):
        s = grades.summary(conn, c.code)
        standing = f"{s['current_percent']}%" if s["current_percent"] is not None else "no grades yet"
        nxt = conn.execute(
            f"""SELECT {EFFECTIVE} FROM items WHERE deleted_at IS NULL AND merged_into IS NULL
                AND COALESCE(user_course, course_code) = ? AND COALESCE(user_status, status) != 'done'
                AND COALESCE(user_due_at, due_at) >= ? ORDER BY COALESCE(user_due_at, due_at) LIMIT 1""",
            (c.code, now.isoformat(timespec="minutes")),
        ).fetchone()
        open_count = conn.execute(
            """SELECT COUNT(*) FROM items WHERE deleted_at IS NULL AND merged_into IS NULL
               AND COALESCE(user_course, course_code) = ? AND COALESCE(user_status, status) != 'done'""",
            (c.code,),
        ).fetchone()[0]
        next_text = f"{nxt['title']} ({datetime.fromisoformat(nxt['due_at']).strftime('%b %d')})" if nxt else "nothing scheduled"
        lines.append(f"| [[Courses/{c.folder}/Course\\|{c.name}]] | {standing} | {s['weight_graded_so_far']}% of grade | {next_text} | {open_count} |")
    lines.append("")

    lines.append("## Workload, next four weeks")
    lines.append("")
    week_start = now.date() - timedelta(days=now.weekday())
    for w in range(4):
        start = week_start + timedelta(days=7 * w)
        end = start + timedelta(days=7)
        rows = conn.execute(
            f"""SELECT kind, {EFFECTIVE} FROM items WHERE deleted_at IS NULL AND merged_into IS NULL
                AND COALESCE(user_status, status) != 'done'
                AND substr(COALESCE(user_due_at, due_at), 1, 10) >= ? AND substr(COALESCE(user_due_at, due_at), 1, 10) < ?""",
            (start.isoformat(), end.isoformat()),
        ).fetchall()
        exams = sum(1 for r in rows if r["kind"] == "exam")
        heavy = sum(1 for r in rows if (r["weight"] or 0) >= 10)
        flag = " **crunch week**" if len(rows) >= 6 or exams >= 2 or (exams >= 1 and heavy >= 2) else ""
        lines.append(f"- Week of {start.strftime('%b %d')}: {len(rows)} item{'s' if len(rows) != 1 else ''}, {exams} exam{'s' if exams != 1 else ''}{flag}")
    lines.append("")

    lines.append("## Connections")
    lines.append("")
    rows = connector_health(conn)
    if not rows:
        lines.append("- No sources synced yet.")
    for r in rows:
        state = "ok" if r["last_ok"] else f"failing: {r['last_error']}"
        lines.append(f"- {r['connector']}: last success {_ago(r['last_success'], now)}, {state}")
    lines.append("")

    recent = conn.execute(
        f"""SELECT c.field, c.old_value, c.new_value, c.detected_at, c.urgency, {EFFECTIVE}
            FROM changes c JOIN items i ON i.id = c.item_id
            WHERE c.detected_at >= ? ORDER BY c.detected_at DESC LIMIT 20""",
        (db.since(now, timedelta(days=7)),),
    ).fetchall()
    lines.append("## Changes this week")
    lines.append("")
    if not recent:
        lines.append("- None.")
    for r in recent:
        day = datetime.fromisoformat(r["detected_at"]).astimezone(cfg.tz).strftime("%a")
        what = {"due_at": "due date moved", "title": "renamed", "deleted": "removed"}.get(r["field"], r["field"])
        flag = " (urgent)" if r["urgency"] == "urgent" else ""
        lines.append(f"- {day}: {r['title']}, {what}{flag}")
    lines.append("")
    return "\n".join(lines) + "\n"


def _ago(iso: str | None, now: datetime) -> str:
    if not iso:
        return "never"
    then = datetime.fromisoformat(iso)
    hours = int((now.astimezone(then.tzinfo) - then).total_seconds() // 3600)
    if hours < 1:
        return "under an hour ago"
    if hours < 48:
        return f"{hours} hour{'s' if hours != 1 else ''} ago"
    return f"{hours // 24} days ago"
