"""Write a CLAUDE.md at the vault root so a Claude Code session opened there knows the layout without exploring.

Regenerated on every sync from the config. Turn off with `write_vault_instructions = false`.
"""

from __future__ import annotations

from pathlib import Path

from .config import Config

TEMPLATE = """# This vault

This is a student's course vault managed by Oso. Use the Oso tools (`list_deadlines`, `read_section`, `read_note`, `grade_summary`, and the rest) and the Oso skills. To find a topic, call `search_notes` (it matches by meaning and exact words across every course and returns the sections themselves); to find a named note, call `list_notes` on the course folder. The Markdown copies next to Office, LibreOffice, and PDF files are what make those searchable.

## Courses

{courses}

## Layout

- Each course lives in `Courses/<term>/<name>/` (for example `Courses/2026 Fall/Calculus II/`) and never moves; finished courses stay put and are left out of default search. It has `Lectures`, `Homework`, `Readings`, `Notes`, `Exams`, and `Handwriting` (tablet and scanned pages; `pages/` under it holds page images). `Canvas/`, `Drive/`, and `Announcements/` are filled by the service.
- `Courses/<course folder>/Course.md` holds the syllabus facts and the course's AI policy.
- Each course's `Books/<title>/` holds a textbook as one note per chapter, every page under a `## p. N` heading; `Book.md` indexes it. The book is the authority over the student's notes; search it with `search_notes` and `source` "book".
- `Clippings/` holds pages clipped with the Web Clipper and not yet filed. `Oso/Alerts.md` is the urgent-change log; `Oso/Skills/` holds the instructions behind each Oso command.
- `Today.md` and `Dashboard.md` are generated by the service; never edit them.
- Files ending in `.md` next to a `.docx`, `.pptx`, `.xlsx`, or `.pdf` are converted copies of that file.

## Which skill

- Set up a course from a syllabus: create-course. Morning briefing: oso-briefing. Recent urgent changes: oso-alerts (the service puts them on the calendar itself).
- Explain a topic: oso-explain. Summarize: oso-summarize. Study guide: oso-study-guide. Quiz or practice test: oso-quiz. Check an attempt: oso-check. Flashcards: oso-flashcards.
- The instructions behind each Oso command are in `Oso/Skills/`; the student may edit them. New versions that clash with their edits: oso-skill-updates.
- What the student knows per topic (shaky, untested, strong, from quiz and check results), and fixing a result recorded wrong: oso-profile; summaries are in `Oso/Profile/`.
- Finish, reopen, or relate courses, or follow an instructor's website: oso-courses. Pages and documents from followed sites are in each course's `Web/` folder.
- Grades and what-if: oso-grades. What Oso read from Canvas (grades, scores, missing work, instructor comments): `canvas_info`. Study plan: oso-plan. Handwriting: run `oso transcribe` (or oso-transcribe). Looking after Oso ("open my settings", "Oso status", update, sync, back up, something broken): oso-doctor.

## Rules

- Cite notes as `[[path]]`. Say so when the notes have nothing relevant; never invent course content.
- Match the size of the request and answer in the chat. Write a file only when the student asks (flashcards are the exception). Never produce submittable answers to graded work; mention the course's AI policy only when it forbids what was asked.
- Prefer `search_notes` results over opening whole files; read more with `read_section` or bounded pieces of `read_note` only when needed. Whole textbooks do not belong in context.
- A note of `type: google-file` is only a pointer; read the Google Doc it links through the Google Drive connector.
- Never edit a note the student wrote by hand.
"""


def write(cfg: Config) -> Path | None:
    if not cfg.write_vault_instructions:
        return None
    rows = [
        f"- **{c.name}** (`{c.code}`{', ' + c.term if c.term else ''}{', finished' if c.finished else ''}): `Courses/{c.folder}/`"
        + (f"; builds on {', '.join(c.related)}" if c.related else "")
        for c in sorted(cfg.courses, key=lambda c: (c.finished, c.term or "", c.name))
    ] or ["- No courses set up yet."]
    path = cfg.vault / "CLAUDE.md"
    text = TEMPLATE.format(courses="\n".join(rows))
    if not path.exists() or path.read_text(encoding="utf-8", errors="replace") != text:
        path.write_text(text, encoding="utf-8")
    return path
