"""Write a CLAUDE.md at the vault root so a Claude Code session opened there knows the layout without exploring.

Regenerated on every sync from the config. Turn off with `write_vault_instructions = false`.
"""

from __future__ import annotations

from pathlib import Path

from .config import Config

TEMPLATE = """# This vault

This is a student's course vault managed by Oso. Use the Oso tools (`list_deadlines`, `read_section`, `read_note`, `grade_summary`, and the rest) and the Oso skills. To find material, search the course's folder with your file search for the key terms; the Markdown copies next to Office, LibreOffice, and PDF files are what make those searchable.

## Courses

{courses}

## Layout

- `Courses/<course folder>/` has `Lectures`, `Homework`, `Readings`, `Notes`, `Exams`, and `Handwriting` (tablet and scanned pages; `pages/` under it holds page images). `Canvas/`, `Drive/`, and `Announcements/` are filled by the service.
- `Courses/<course folder>/Course.md` holds the syllabus facts and the course's AI policy.
- `Inbox/` holds clipped pages not yet filed and `Inbox/Alerts.md`, the urgent-change log.
- `Today.md` and `Dashboard.md` are generated by the service; never edit them.
- Files ending in `.md` next to a `.docx`, `.pptx`, `.xlsx`, or `.pdf` are converted copies of that file.

## Which skill

- Set up a course from a syllabus: create-course. Morning briefing: oso-briefing. Recent urgent changes: oso-alerts (the service puts them on the calendar itself).
- Explain a topic: oso-explain. Summarize: oso-summarize. Study guide: oso-study-guide. Practice test: oso-quiz. Check an attempt: oso-check. Flashcards: oso-flashcards.
- Grades and what-if: oso-grades. Study plan: oso-plan. Handwriting: run `oso transcribe` (or oso-transcribe). Something broken: oso-doctor.

## Rules

- Cite notes as `[[path]]`. Say so when the notes have nothing relevant; never invent course content.
- State the course's AI policy at the start of tutoring. Never produce submittable answers to graded work.
- Search within `Courses/<course folder>/`, then read the matching section (`read_section`) or bounded pieces (`read_note`); whole textbooks do not belong in context.
- A note of `type: google-file` is only a pointer; read the Google Doc it links through the Google Drive connector.
- Never edit a note the student wrote by hand.
"""


def write(cfg: Config) -> Path | None:
    if not cfg.write_vault_instructions:
        return None
    rows = [f"- **{c.name}** (`{c.code}`): `Courses/{c.folder}/`" for c in sorted(cfg.courses, key=lambda c: c.name)] or ["- No courses set up yet."]
    path = cfg.vault / "CLAUDE.md"
    text = TEMPLATE.format(courses="\n".join(rows))
    if not path.exists() or path.read_text(encoding="utf-8", errors="replace") != text:
        path.write_text(text, encoding="utf-8")
    return path
