"""Write Today.md into the vault: the facts the morning briefing is built from.

The file is regenerated on every sync. Nothing in it is written by hand.
"""

from __future__ import annotations

import sqlite3
from datetime import datetime, timedelta
from pathlib import Path

from .config import Config
from .db import EFFECTIVE

STALE = timedelta(hours=24)


def render(conn: sqlite3.Connection, cfg: Config, now: datetime) -> str:
    today = now.date()
    week_end = today + timedelta(days=7)
    lines = [
        "---",
        "type: oso-today",
        f"generated: {now.isoformat(timespec='minutes')}",
        "---",
        "",
        f"# Today, {today.strftime('%A %B %d')}",
        "",
        "Generated by Oso. Do not edit; it is rewritten on every check.",
        "",
    ]

    open_items = [r for r in _open_items(conn) if cfg.is_active(r["course_code"])]
    overdue = [r for r in open_items if r["due"] and r["due"].date() < today]
    due_today = [r for r in open_items if r["due"] and r["due"].date() == today]
    this_week = [r for r in open_items if r["due"] and today < r["due"].date() <= week_end]
    exams = [r for r in open_items if r["kind"] == "exam" and r["due"] and r["due"].date() >= today]

    not_started = [r for r in open_items if r["due"] and r["status"] == "not_started" and now <= r["due"] <= now + timedelta(hours=24)]
    if not_started:
        lines.append("## Not started yet")
        for r in not_started:
            lines.append(f"- {_course_label(r, cfg)}{r['title']} is due within a day and is not marked started.")
        lines.append("")

    lines += _section("Overdue", overdue, cfg, now)
    lines += _canvas_sign_in(conn)
    lines += _section("Due today", due_today, cfg, now)
    lines += _readiness(conn, cfg, now)
    lines += _missing(conn, cfg)
    lines += _section("Due this week", this_week, cfg, now)

    lines.append("## Exams")
    if exams:
        for r in exams:
            days = (r["due"].date() - today).days
            when = "today" if days == 0 else f"in {days} day{'s' if days != 1 else ''}"
            lines.append(f"- {_course_label(r, cfg)}{r['title']}: {r['due'].strftime('%a %b %d')} ({when})")
    else:
        lines.append("- No exams scheduled.")
    lines.append("")

    lines += _changes(conn, cfg, now)
    lines += _canvas_events(conn, cfg, now)
    lines += _site_lines(conn, cfg, now)
    lines += _handwriting(conn)
    lines += _update_note(conn)
    lines += _skill_note()
    lines += _finished_note(conn, cfg, now)
    lines += _reading_note(conn, cfg, now)
    lines += _backup_note(conn, cfg, now)
    lines += _health(conn, now, timedelta(hours=cfg.stale_hours))
    return "\n".join(lines) + "\n"


def write(conn: sqlite3.Connection, cfg: Config, now: datetime) -> Path:
    path = cfg.vault / "Today.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(conn, cfg, now), encoding="utf-8")
    return path


def _open_items(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        f"""SELECT id, kind, url, {EFFECTIVE} FROM items
            WHERE deleted_at IS NULL AND merged_into IS NULL
            ORDER BY due_at"""
    ).fetchall()
    out = []
    for r in rows:
        if r["status"] == "done":
            continue
        due = datetime.fromisoformat(r["due_at"]) if r["due_at"] else None
        out.append({"id": r["id"], "kind": r["kind"], "title": r["title"], "due": due, "status": r["status"],
                    "weight": r["weight"], "course_code": r["course_code"], "url": r["url"]})
    return out


def _section(heading: str, rows: list[dict], cfg: Config, now: datetime) -> list[str]:
    lines = [f"## {heading}"]
    if not rows:
        lines.append("- Nothing.")
    for r in rows:
        when = r["due"].strftime("%a %b %d") if r["due"] else "no date"
        if r["due"] and r["due"].time() != r["due"].replace(hour=23, minute=59).time():
            when += r["due"].strftime(" %I:%M %p").replace(" 0", " ")
        extra = ""
        if r["weight"]:
            extra = f", {r['weight']:g}% of grade"
        if r["status"] == "started":
            extra += ", started"
        link = f" [open]({r['url']})" if r["url"] else ""
        lines.append(f"- {_course_label(r, cfg)}{r['title']} ({r['kind']}), {when}{extra}{link}")
    lines.append("")
    return lines


def _canvas_sign_in(conn: sqlite3.Connection) -> list[str]:
    from . import canvas_session

    try:
        if canvas_session.status(conn) == "needs_sign_in":
            return ["## Canvas", f"- {canvas_session.SIGN_IN_LINE}", ""]
    except Exception:  # noqa: BLE001
        pass
    return []


def _missing(conn: sqlite3.Connection, cfg: Config) -> list[str]:
    from . import canvas_store

    try:
        rows = canvas_store.missing_work(conn, cfg)
    except sqlite3.Error:
        return []
    if not rows:
        return []
    lines = ["## Missing work"]
    for r in rows:
        c = cfg.course_for(r["course"])
        lines.append(f"- **{c.name if c else r['course']}**: {r['name']} is marked missing in Canvas.")
    lines.append("")
    return lines


def _canvas_events(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import canvas_store

    try:
        rows = canvas_store.recent_events(conn, now)
        untagged = canvas_store.untagged_count(conn, cfg)
    except sqlite3.Error:
        return []
    lines = []
    if rows:
        lines.append("## From Canvas")
        for r in rows:
            c = cfg.course_for(r["course"])
            lines.append(f"- **{c.name if c else r['course']}**: {r['text']}.")
        lines.append("")
    if untagged:
        lines += ["## Oso", f"- {untagged} Canvas assignment{'s' if untagged != 1 else ''} not yet matched to course topics; Claude does this during the briefing.", ""]
    return lines


def _site_lines(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import sites

    try:
        events = sites.recent_events(conn, now)
        trouble = sites.problems(conn, cfg)
    except sqlite3.Error:
        return []
    lines = []
    if events or trouble:
        lines.append("## From instructors' websites")
        for r in events:
            c = cfg.course_for(r["course"])
            lines.append(f"- **{c.name if c else r['course']}**: {r['text']}.")
        lines += [f"- {t}" for t in trouble]
        lines.append("")
    return lines


def _readiness(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import readiness

    try:
        return readiness.section(conn, cfg, now)
    except sqlite3.Error:
        return []


def _course_label(r: dict, cfg: Config) -> str:
    c = cfg.course_for(r["course_code"])
    name = c.name if c else (r["course_code"] or "")
    return f"**{name}**: " if name else ""


def _changes(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    since = (now - timedelta(hours=36)).isoformat(timespec="seconds")
    rows = conn.execute(
        f"""SELECT c.field, c.old_value, c.new_value, c.urgency, c.detected_at, i.kind, i.url, {EFFECTIVE}
            FROM changes c JOIN items i ON i.id = c.item_id
            WHERE c.detected_at >= ? ORDER BY c.detected_at DESC""",
        (since,),
    ).fetchall()
    lines = ["## Changes since yesterday"]
    if not rows:
        lines.append("- Nothing changed.")
    for r in rows:
        label = _course_label(r, cfg)
        if r["field"] == "due_at":
            old = _fmt(r["old_value"])
            new = _fmt(r["new_value"])
            text = f"{label}{r['title']} moved from {old} to {new}"
        elif r["field"] == "title":
            text = f"{label}'{r['old_value']}' was renamed to '{r['new_value']}'"
        elif r["field"] == "deleted":
            text = f"{label}{r['title']} was removed from its source"
        else:
            text = f"{label}{r['title']}: {r['field']} changed"
        flag = " **(urgent)**" if r["urgency"] == "urgent" else ""
        lines.append(f"- {text}{flag}")
    lines.append("")
    return lines


def _fmt(iso: str | None) -> str:
    if not iso:
        return "no date"
    try:
        return datetime.fromisoformat(iso).strftime("%a %b %d")
    except ValueError:
        return iso


def _update_note(conn: sqlite3.Connection) -> list[str]:
    try:
        row = conn.execute("SELECT value FROM meta WHERE key = 'update_message'").fetchone()
    except sqlite3.OperationalError:
        return []
    if not row or not row["value"]:
        return []
    return ["## Oso", f"- {row['value']}", ""]


def _backup_note(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import backup

    try:
        line = backup.stale_line(conn, cfg, now)
    except Exception:  # noqa: BLE001
        return []
    return ["## Backup", f"- {line}", ""] if line else []


def _reading_note(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import reader

    try:
        n = len(reader.waiting(cfg, conn, now)) + reader.handwriting_waiting(conn)
    except Exception:  # noqa: BLE001
        return []
    if not n:
        return []
    pages = f"{n} page{'s' if n != 1 else ''} with handwriting, equations, tables, or drawings"
    if not cfg.auto_read:
        line = f"{pages} are waiting for Claude. Turn on automatic reading in oso settings, or run 'oso transcribe'."
    elif reader._claude() is None:
        line = f"{pages} are waiting, but Claude Code isn't installed on this computer, so Oso can't have them read. Install it from claude.ai/code."
    else:
        line = f"Claude is reading {pages} in the background."
    return ["## Reading", f"- {line}", ""]


def _finished_note(conn: sqlite3.Connection, cfg: Config, now: datetime) -> list[str]:
    from . import courses

    over = courses.looks_finished(conn, cfg, now)
    if not over:
        return []
    names = ", ".join(c.name for c in over)
    return ["## Courses", f"- {names} {'has' if len(over) == 1 else 'have'} had nothing due for two weeks. If the semester is over, ask Claude to mark {'it' if len(over) == 1 else 'them'} finished.", ""]


def _skill_note() -> list[str]:
    from . import skillsync

    try:
        names = skillsync.conflicts()
    except OSError:
        return []
    if not names:
        return []
    which = ", ".join(n.removeprefix("oso-") for n in names)
    return ["## Oso commands", f"- Oso has a new version of commands you changed ({which}). Ask Claude to go through the Oso command updates.", ""]


def _handwriting(conn: sqlite3.Connection) -> list[str]:
    from . import handwriting

    pending = handwriting.pending(conn, limit=200)
    low = handwriting.low_confidence(conn)
    if not pending and not low:
        return []
    lines = ["## Handwritten notes"]
    if pending:
        notebooks = sorted({p["notebook"] for p in pending})
        lines.append(f"- {len(pending)} page{'s' if len(pending) != 1 else ''} waiting to be transcribed: {', '.join(notebooks)}. Run the transcribe skill in Claude Code.")
    for p in low:
        lines.append(f"- Page {p['page']} of {p['notebook']} transcribed with low confidence; check [[{p['note_path']}]].")
    lines.append("")
    return lines


def _health(conn: sqlite3.Connection, now: datetime, stale: timedelta = STALE) -> list[str]:
    from .db import connector_health

    rows = connector_health(conn)
    lines = ["## Connections"]
    if not rows:
        lines.append("- No sources have been synced yet. Run 'oso init' to add the Canvas calendar feed.")
    for r in rows:
        name = _friendly(r["connector"])
        if r["connector"] == "remarkable_usb":
            lines.append(_tablet_line(conn, now))
            continue
        last_ok = datetime.fromisoformat(r["last_success"]) if r["last_success"] else None
        if last_ok is None:
            lines.append(f"- {name} has never synced successfully. Last error: {r['last_error'] or 'unknown'}.")
        elif now.astimezone(last_ok.tzinfo) - last_ok > stale:
            hours = int((now.astimezone(last_ok.tzinfo) - last_ok).total_seconds() // 3600)
            lines.append(f"- {name} has not synced in {hours} hours. Last error: {r['last_error'] or 'unknown'}. Deadlines from it may be out of date.")
        elif not r["last_ok"]:
            lines.append(f"- {name} failed on its last try ({r['last_error'] or 'unknown'}) but synced within the last day.")
        else:
            lines.append(f"- {name} is up to date.")
    lines.append("")
    return lines


def _tablet_line(conn: sqlite3.Connection, now: datetime) -> str:
    from .connectors.remarkable_usb import last_pull

    t = last_pull(conn)
    if t is None:
        return "- reMarkable has not been pulled yet. Plug the tablet in by USB with the USB web interface turned on, with a folder on it named after each course."
    days = (now.astimezone(t.tzinfo) - t).days
    if days >= 3:
        return f"- reMarkable was last pulled {days} days ago. Plug it in to bring new notes over."
    return "- reMarkable notes are up to date."


def _friendly(connector: str) -> str:
    return {"canvas_feed": "Canvas calendar feed", "canvas_api": "Canvas (token)", "remarkable_usb": "reMarkable", "google_calendar": "Google Calendar alerts"}.get(connector, connector)
